### ISSUE TITLE
Default Web browser does not work

### ISSUE THREAD

**Issue by maxwellnie** [lesca/lemoe#2]
I tried to run default web browser,but prompt me "Failed execute default web browser:input/output error".

**Comment by maxwellnie** [comment]
![Screenshot_2024-05-23-23-15-29-378_com termux x11-edit](https://github.com/lesca/lemoe/assets/77709815/4fdee6e0-b102-420a-ae38-9580342a3c04)

**Comment by maxwellnie** [comment]
This program caused idea to be unable to log in using the default web browser.

**Comment by maxwellnie** [comment]
This problem caused idea to be unable to log in using the default web browser.

**Comment by lesca** [comment]
Hello,

You can use commands below to fix this:

```
xdg-mime default chromium.desktop x-scheme-handler/https
xdg-mime default chromium.desktop x-scheme-handler/http
```

However, this is more related to the distribution not the `lemoe` project. The project is amied to provide a framework to build, run, and manage the distributions. 

For distribution issues, you can fix by applying a PR.
refer to [fix](https://github.com/lesca/lemoe/commit/c7ab0e37f97d585f09ba5bfa7f7112638c19efe6) and [development guide](https://github.com/lesca/lemoe?tab=readme-ov-file#development-guide)

NB: The new released pack and base image also includes this fix.

**Comment by maxwellnie** [comment]
But the image source is a "README.md" link.
